### ISSUE TITLE
Potential addition to the default blacklists: Red Whip 

### ISSUE THREAD

**Issue by Laudenum** [Moffein/AI_Blacklist#1]
Some mobs like Jellyfish will have a permanent Red Whip effect even when under the effects of DoT debuffs like Ignite or Bleed.
Although I can't confirm for certain due to my lack of experience with RoR2 console debugging, if the Red Whip is permanently on for Vengeance Dopplegangers this can lead to some very broken, instagib scenarios of sudden death.
As such the Red Whip is a candidate for being a default item that ought to be blacklisted.

**Comment by Moffein** [comment]
Red Whip's buff gets removed when attacking, rather than on taking damage.

**Comment by Laudenum** [comment]
Oh I see. For the player the buff gets removed when any of those two conditions are met whereas for hostile mobs it only when they attack. As per the item's description I'd say this is a bug that entails the item being blacklisted by default because if they are taking damage then they are most certainly in a combat situation (and combat-like situation in the case of Glowing Meteorite).

**Comment by Moffein** [comment]
Red Whip's buff got changed to only be removed when using Combat Skills in the Hidden Realms Update. The item is working as intended, and it's nowhere near as impactful or game breaking as a lot of other non-blacklisted items in Vanilla.
