### ISSUE TITLE
Thunderstore.io page lists a non working URL for item codenames.

### ISSUE THREAD

**Issue by RetroNutcase** [Moffein/AI_Blacklist#2]
https://github.com/risk-of-thunder/R2Wiki/wiki/Item-&-Equipment-IDs-and-Names 
is a blank page. Unable to get an item list from it as a result.

**Comment by Moffein** [comment]
I'll update the mod readme.
Use https://thunderstore.io/package/IHarbHD/DebugToolkit/ and enter list_item into console to get a list of all the internal itemnames.
